"""empty message

Revision ID: c90f2fb01ff8
Revises: bdcbff6e1f32
Create Date: 2022-10-17 10:35:25.710910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90f2fb01ff8'
down_revision = 'bdcbff6e1f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feedback_customer_key', 'feedback', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('feedback_customer_key', 'feedback', ['customer'])
    # ### end Alembic commands ###
